site_name: iRails Docs
site_url: ""
use_directory_urls: false
plugins: []

nav:
    - Getting Start: index.md
    - controller: controller.md
    - model: model.md
    - service: service.md
    - view: view.md
theme: 
  name: readthedocs
  # locale: zh