site_name: iRails 
site_url: ""
use_directory_urls: false
plugins: []
extra_css:
    - css/css.css

nav:
    - Getting Start: index.md
    - Controllers: controllers.md
    - Models: models.md
    - Services: services.md
    - Views: views.md
 
    - Auth System: auth.md
theme: 
  name: readthedocs
  # locale: zh